version: '2'
services:
    web:
        build:
            dockerfile: ./docker/web.Dockerfile
            context: ./../
            args:
                - MIR_WWW_PATH=/var/www/html/miwifiradio/
                - MIR_DOMAIN_NAME=192.168.1.132
        image: miradio-web
        container_name: miradio-web
        env_file:
            - ".env"
        ports:
            - "80:80"
            - "444:443"
        depends_on:
            - mysqldb
    myadmin:
        image: arm64v8/phpmyadmin:latest
        container_name: miradio-phpmyadmin
        ports:
            - "81:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=192.168.1.132
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        build:
            dockerfile: ./docker/db.Dockerfile
            context: ./../
        image: miradio-db
        container_name: miradio-db
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=miradio
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        ports:
            - "3306:3306"
